# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentsecrets < Formula
  desc "Zero-knowledge credential firewall for the AI era"
  homepage "https://github.com/The-17/agentsecrets"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/The-17/agentsecrets/releases/download/v1.1.0/agentsecrets_1.1.0_darwin_amd64.tar.gz"
      sha256 "9a81eb555c367e190923ee0e00c428d25c5b7747abf92cd0ad43b627408a9034"

      define_method(:install) do
        bin.install "agentsecrets"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/The-17/agentsecrets/releases/download/v1.1.0/agentsecrets_1.1.0_darwin_arm64.tar.gz"
      sha256 "ca79877304d9711afb1fd62bc629a30037c0ad4fb7638718de3e5616e8fa07fd"

      define_method(:install) do
        bin.install "agentsecrets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-17/agentsecrets/releases/download/v1.1.0/agentsecrets_1.1.0_linux_amd64.tar.gz"
      sha256 "ba679b1009f0f950a6f156c56b801e2d1e5065e390ccaaf429b17f71e82c8dae"
      define_method(:install) do
        bin.install "agentsecrets"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-17/agentsecrets/releases/download/v1.1.0/agentsecrets_1.1.0_linux_arm64.tar.gz"
      sha256 "50e8cb0990422d871b668102794387957b08e3d9189a6b162a51e52588bf4dcf"
      define_method(:install) do
        bin.install "agentsecrets"
      end
    end
  end

  test do
    system "#{bin}/agentsecrets --version"
  end
end
