# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentsecrets < Formula
  desc "Zero-knowledge credential firewall for the AI era"
  homepage "https://github.com/The-17/agentsecrets"
  version "3.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/The-17/agentsecrets/releases/download/v3.1.5/agentsecrets_3.1.5_darwin_amd64.tar.gz"
      sha256 "3d9e44855011e2e74bee053779f9d19112d3ae1feae461529ae6592907531739"

      define_method(:install) do
        bin.install "agentsecrets"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/The-17/agentsecrets/releases/download/v3.1.5/agentsecrets_3.1.5_darwin_arm64.tar.gz"
      sha256 "caed9d5fc623d083cceecff2bc39e05b4a50fd8c55cbb20ed39b42539e2b81ef"

      define_method(:install) do
        bin.install "agentsecrets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-17/agentsecrets/releases/download/v3.1.5/agentsecrets_3.1.5_linux_amd64.tar.gz"
      sha256 "aa7402744f4e9ced8e730f9777820c0e0de0a6f2bae2edfbae760091bb22055a"
      define_method(:install) do
        bin.install "agentsecrets"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-17/agentsecrets/releases/download/v3.1.5/agentsecrets_3.1.5_linux_arm64.tar.gz"
      sha256 "15a3bc43bf45cbdbf2de576c2dbd2c045cc92bf79739618120ae71ed64659880"
      define_method(:install) do
        bin.install "agentsecrets"
      end
    end
  end

  test do
    system "#{bin}/agentsecrets --version"
  end
end
