# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentsecrets < Formula
  desc "Zero-knowledge credential proxy for AI agents"
  homepage "https://github.com/The-17/agentsecrets"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/The-17/agentsecrets/releases/download/v1.0.0/agentsecrets_1.0.0_darwin_amd64.tar.gz"
      sha256 "afc3b534c31b0da506f856b35d1fd6786a7b31136895854fbf87222ec4a3e7fe"

      define_method(:install) do
        bin.install "agentsecrets"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/The-17/agentsecrets/releases/download/v1.0.0/agentsecrets_1.0.0_darwin_arm64.tar.gz"
      sha256 "aab31f05f9636ed8da61507e0da51ac54892bb5ec3cee83d4e8d3abcb21ee51e"

      define_method(:install) do
        bin.install "agentsecrets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-17/agentsecrets/releases/download/v1.0.0/agentsecrets_1.0.0_linux_amd64.tar.gz"
      sha256 "5d0e2f2a2e7ec750dcb5bc241da8b732292c11d987fa0361698eb57421871e69"
      define_method(:install) do
        bin.install "agentsecrets"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-17/agentsecrets/releases/download/v1.0.0/agentsecrets_1.0.0_linux_arm64.tar.gz"
      sha256 "b40deb8d4d23a410a24139510fd038769a52382971763a2d21bd5af02d94ce4e"
      define_method(:install) do
        bin.install "agentsecrets"
      end
    end
  end

  test do
    system "#{bin}/agentsecrets --version"
  end
end
