# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KeychainAuth < Formula
  desc "Security policy daemon for AgentSecrets"
  homepage "https://agentsecrets.theseventeen.co"
  version "3.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/The-17/keychain-auth/releases/download/v3.0.0/keychain-auth_3.0.0_darwin_amd64.tar.gz"
      sha256 "15cbc588eb27cfaac9584246b1569c97aea370ded9928c49c21e543a1525701f"

      define_method(:install) do
        bin.install "keychain-auth"
        if OS.mac?
          (prefix/"io.keychainauth.daemon.plist").install "init/io.keychainauth.daemon.plist"
        elsif OS.linux?
          (prefix/"keychain-auth.service").install "init/keychain-auth.service"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/The-17/keychain-auth/releases/download/v3.0.0/keychain-auth_3.0.0_darwin_arm64.tar.gz"
      sha256 "df6d7b4ae3ceadc6dc3b63d9a982bbc368e4fcdca94b025b52e713f800a64e91"

      define_method(:install) do
        bin.install "keychain-auth"
        if OS.mac?
          (prefix/"io.keychainauth.daemon.plist").install "init/io.keychainauth.daemon.plist"
        elsif OS.linux?
          (prefix/"keychain-auth.service").install "init/keychain-auth.service"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-17/keychain-auth/releases/download/v3.0.0/keychain-auth_3.0.0_linux_amd64.tar.gz"
      sha256 "3f82a6e0f440650d091f5f5d30e3d2e028410cec6a852363e2ce4d6cc910ab01"
      define_method(:install) do
        bin.install "keychain-auth"
        if OS.mac?
          (prefix/"io.keychainauth.daemon.plist").install "init/io.keychainauth.daemon.plist"
        elsif OS.linux?
          (prefix/"keychain-auth.service").install "init/keychain-auth.service"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-17/keychain-auth/releases/download/v3.0.0/keychain-auth_3.0.0_linux_arm64.tar.gz"
      sha256 "037028846c8abbb1a1f9f8aa0242adb6f24eb8163c4071723069a14c8ad4a9bb"
      define_method(:install) do
        bin.install "keychain-auth"
        if OS.mac?
          (prefix/"io.keychainauth.daemon.plist").install "init/io.keychainauth.daemon.plist"
        elsif OS.linux?
          (prefix/"keychain-auth.service").install "init/keychain-auth.service"
        end
      end
    end
  end

  test do
    system "#{bin}/keychain-auth --version"
  end
end
