# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KeychainAuth < Formula
  desc "Security policy daemon for AgentSecrets"
  homepage "https://agentsecrets.theseventeen.co"
  version "3.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/The-17/keychain-auth/releases/download/v3.2.0/keychain-auth_3.2.0_darwin_amd64.tar.gz"
      sha256 "4e29ad4f469f37a933ccf39b247882c987502fa69ff3ae772518dfb80828c45a"

      define_method(:install) do
        bin.install "keychain-auth"
        if OS.mac?
          (prefix/"io.keychainauth.daemon.plist").install "init/io.keychainauth.daemon.plist"
        elsif OS.linux?
          (prefix/"keychain-auth.service").install "init/keychain-auth.service"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/The-17/keychain-auth/releases/download/v3.2.0/keychain-auth_3.2.0_darwin_arm64.tar.gz"
      sha256 "bf5a0cdb36addce7b7fc0b16b0c7326a6b24c31ca74f856d64bca5a8f349fef4"

      define_method(:install) do
        bin.install "keychain-auth"
        if OS.mac?
          (prefix/"io.keychainauth.daemon.plist").install "init/io.keychainauth.daemon.plist"
        elsif OS.linux?
          (prefix/"keychain-auth.service").install "init/keychain-auth.service"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-17/keychain-auth/releases/download/v3.2.0/keychain-auth_3.2.0_linux_amd64.tar.gz"
      sha256 "30c7312e3bc692df16b9a56fe0cdcfb6189889f739510da26a53f98ca5b5ced9"
      define_method(:install) do
        bin.install "keychain-auth"
        if OS.mac?
          (prefix/"io.keychainauth.daemon.plist").install "init/io.keychainauth.daemon.plist"
        elsif OS.linux?
          (prefix/"keychain-auth.service").install "init/keychain-auth.service"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-17/keychain-auth/releases/download/v3.2.0/keychain-auth_3.2.0_linux_arm64.tar.gz"
      sha256 "90735377d96d7e8567ea2cd5739291ec0489e534110bbc7c3442821ad99d7112"
      define_method(:install) do
        bin.install "keychain-auth"
        if OS.mac?
          (prefix/"io.keychainauth.daemon.plist").install "init/io.keychainauth.daemon.plist"
        elsif OS.linux?
          (prefix/"keychain-auth.service").install "init/keychain-auth.service"
        end
      end
    end
  end

  test do
    system "#{bin}/keychain-auth --version"
  end
end
