# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KeychainAuth < Formula
  desc "Security policy daemon for AgentSecrets"
  homepage "https://agentsecrets.theseventeen.co"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/The-17/keychain-auth/releases/download/v0.1.3/keychain-auth_0.1.3_darwin_amd64.tar.gz"
      sha256 "62e61c4df330ece5467fe8430fb0182fd327ba9cf9db535517ebd3c5a3a87771"

      define_method(:install) do
        bin.install "keychain-auth"
        if OS.mac?
          (prefix/"io.keychainauth.daemon.plist").install "init/io.keychainauth.daemon.plist"
        elsif OS.linux?
          (prefix/"keychain-auth.service").install "init/keychain-auth.service"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/The-17/keychain-auth/releases/download/v0.1.3/keychain-auth_0.1.3_darwin_arm64.tar.gz"
      sha256 "7215936271bdb1a25ae6b00c32da04f3ff4b4a3df342c48377d7325ca519089b"

      define_method(:install) do
        bin.install "keychain-auth"
        if OS.mac?
          (prefix/"io.keychainauth.daemon.plist").install "init/io.keychainauth.daemon.plist"
        elsif OS.linux?
          (prefix/"keychain-auth.service").install "init/keychain-auth.service"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-17/keychain-auth/releases/download/v0.1.3/keychain-auth_0.1.3_linux_amd64.tar.gz"
      sha256 "6fd730ed8ea40b7e26897bb712a6b6f1c0241b9ba6568df367af01a11755c661"
      define_method(:install) do
        bin.install "keychain-auth"
        if OS.mac?
          (prefix/"io.keychainauth.daemon.plist").install "init/io.keychainauth.daemon.plist"
        elsif OS.linux?
          (prefix/"keychain-auth.service").install "init/keychain-auth.service"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-17/keychain-auth/releases/download/v0.1.3/keychain-auth_0.1.3_linux_arm64.tar.gz"
      sha256 "2c4d129f40aaed5cf33ba85e25288603aae4de093b0de5129fdf9c3f5c39bef4"
      define_method(:install) do
        bin.install "keychain-auth"
        if OS.mac?
          (prefix/"io.keychainauth.daemon.plist").install "init/io.keychainauth.daemon.plist"
        elsif OS.linux?
          (prefix/"keychain-auth.service").install "init/keychain-auth.service"
        end
      end
    end
  end

  test do
    system "#{bin}/keychain-auth --version"
  end
end
