# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sec < Formula
  desc "Signed Execution Contracts (SEC) capability sandbox for agents."
  homepage "https://github.com/The-17/sec"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/The-17/SEC/releases/download/v1.0.0/sec_1.0.0_darwin_amd64.tar.gz"
      sha256 "d1defd6edb391808cec161695c10dc3e2c54e26e731f00e96556c18920e1e1b9"

      define_method(:install) do
        bin.install "sec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/The-17/SEC/releases/download/v1.0.0/sec_1.0.0_darwin_arm64.tar.gz"
      sha256 "30e58b61aac974bee7396077948a0b953ff0aa38a7c0bf7814d76d07ad44305a"

      define_method(:install) do
        bin.install "sec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-17/SEC/releases/download/v1.0.0/sec_1.0.0_linux_amd64.tar.gz"
      sha256 "16d1af76b190ea8f8edc1b41a2c599601c5decc302d814d866148a342d8d97a2"
      define_method(:install) do
        bin.install "sec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/The-17/SEC/releases/download/v1.0.0/sec_1.0.0_linux_arm64.tar.gz"
      sha256 "8857a22cab0985656aaebbfaabe25494f244686f77f954ab2d8f844c65dfdb3d"
      define_method(:install) do
        bin.install "sec"
      end
    end
  end

  test do
    system "#{bin}/sec version"
  end
end
